import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useState } from "react";
import { toast } from "sonner";
import { SiteLayout } from "@/components/layout/SiteLayout";
import { generateLessonPack, setCurrentPack, type LessonInput } from "@/lib/lesson";
import { Sparkles, Loader2 } from "lucide-react";

export const Route = createFileRoute("/create")({
  head: () => ({
    meta: [
      { title: "Create Lesson Pack — EduBox Agent Studio" },
      { name: "description", content: "Generate a complete EduBox-ready lesson pack with AI." },
    ],
  }),
  component: CreatePage,
});

const SUBJECTS = ["Biology", "Mathematics", "Health Education", "Digital Literacy", "Physics", "Chemistry", "English", "History", "Geography"];
const GRADES = ["Primary 4", "Primary 5", "Primary 6", "Grade 6", "Form 1", "Form 2", "Form 3", "Secondary School"];
const LANGUAGES = ["English", "French", "Swahili", "Hausa", "Arabic", "Portuguese"];
const LEVELS = ["Beginner", "Intermediate", "Advanced"];

function CreatePage() {
  const navigate = useNavigate();
  const [loading, setLoading] = useState(false);
  const [form, setForm] = useState<LessonInput>({
    topic: "Photosynthesis",
    subject: "Biology",
    grade: "Form 2",
    country: "Kenya",
    language: "English",
    difficulty: "Beginner",
    objective: "Students should understand how plants make their own food.",
  });

  const onSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!form.topic.trim()) {
      toast.error("Please enter a topic.");
      return;
    }
    setLoading(true);
    // Simulate agent workflow
    await new Promise((r) => setTimeout(r, 1400));
    const pack = generateLessonPack(form);
    setCurrentPack(pack);
    setLoading(false);
    toast.success("Lesson pack generated by 6 agents.");
    navigate({ to: "/generated" });
  };

  const Field = ({ label, children }: { label: string; children: React.ReactNode }) => (
    <label className="block">
      <span className="mb-1.5 block text-sm font-medium text-foreground">{label}</span>
      {children}
    </label>
  );
  const inputCls = "w-full rounded-xl border border-border bg-card px-4 py-2.5 text-sm text-foreground outline-none transition focus:border-[color:var(--color-brand-blue)] focus:ring-2 focus:ring-[color:var(--color-brand-blue)]/20";

  return (
    <SiteLayout>
      <section className="mx-auto max-w-5xl px-5 pt-12 pb-16">
        <div className="mb-8">
          <div className="inline-flex items-center gap-2 rounded-full border border-border bg-card px-3 py-1 text-xs font-medium text-muted-foreground">
            <Sparkles className="h-3.5 w-3.5 text-brand-green" /> Step 1 — Tell the agents about your class
          </div>
          <h1 className="mt-3 text-3xl font-bold tracking-tight md:text-4xl">Create a Lesson Pack</h1>
          <p className="mt-2 text-muted-foreground">Enter your lesson context. The Curriculum, Lesson Builder, Quiz, Teacher Support, EduBox Packaging and Evidence agents will assemble a complete pack.</p>
        </div>

        <form onSubmit={onSubmit} className="rounded-3xl border border-border bg-card p-6 shadow-sm md:p-8">
          <div className="grid gap-5 md:grid-cols-2">
            <Field label="Topic">
              <input className={inputCls} value={form.topic} onChange={(e) => setForm({ ...form, topic: e.target.value })} placeholder="e.g. Photosynthesis" />
            </Field>
            <Field label="Subject">
              <select className={inputCls} value={form.subject} onChange={(e) => setForm({ ...form, subject: e.target.value })}>
                {SUBJECTS.map((s) => <option key={s}>{s}</option>)}
              </select>
            </Field>
            <Field label="Grade level">
              <select className={inputCls} value={form.grade} onChange={(e) => setForm({ ...form, grade: e.target.value })}>
                {GRADES.map((s) => <option key={s}>{s}</option>)}
              </select>
            </Field>
            <Field label="Country or curriculum context">
              <input className={inputCls} value={form.country} onChange={(e) => setForm({ ...form, country: e.target.value })} placeholder="e.g. Kenya, CBC" />
            </Field>
            <Field label="Language">
              <select className={inputCls} value={form.language} onChange={(e) => setForm({ ...form, language: e.target.value })}>
                {LANGUAGES.map((s) => <option key={s}>{s}</option>)}
              </select>
            </Field>
            <Field label="Difficulty level">
              <select className={inputCls} value={form.difficulty} onChange={(e) => setForm({ ...form, difficulty: e.target.value })}>
                {LEVELS.map((s) => <option key={s}>{s}</option>)}
              </select>
            </Field>
            <div className="md:col-span-2">
              <Field label="Learning objective / teacher note">
                <textarea rows={3} className={inputCls} value={form.objective} onChange={(e) => setForm({ ...form, objective: e.target.value })} placeholder="What should students be able to do at the end of the lesson?" />
              </Field>
            </div>
          </div>

          <div className="mt-8 flex items-center justify-between gap-4">
            <p className="text-xs text-muted-foreground">Demo generation flow — a structured lesson-pack simulation. Gemini-ready architecture: API wiring lives in <code className="rounded bg-muted px-1.5 py-0.5">src/lib/lesson.ts</code>.</p>
            <button
              type="submit"
              disabled={loading}
              className="inline-flex items-center gap-2 rounded-full bg-primary px-6 py-3 text-sm font-semibold text-primary-foreground shadow-sm transition hover:opacity-90 disabled:opacity-70"
            >
              {loading ? <><Loader2 className="h-4 w-4 animate-spin" /> Agents working…</> : <><Sparkles className="h-4 w-4" /> Generate Lesson Pack</>}
            </button>
          </div>
        </form>
      </section>
    </SiteLayout>
  );
}