import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { SiteLayout } from "@/components/layout/SiteLayout";
import { getCurrentPack, packToMarkdown, savePack, type LessonPack } from "@/lib/lesson";
import { BrandMark } from "@/components/brand/Logo";
import { Copy, Download, FileText, Package, Printer, Save, Sparkles } from "lucide-react";

export const Route = createFileRoute("/generated")({
  head: () => ({
    meta: [
      { title: "Generated Lesson Pack — EduBox Agent Studio" },
      { name: "description", content: "Your AI-generated, EduBox-ready lesson pack." },
    ],
  }),
  component: GeneratedPage,
});

function GeneratedPage() {
  const [pack, setPack] = useState<LessonPack | undefined>();
  useEffect(() => setPack(getCurrentPack()), []);

  if (!pack) {
    return (
      <SiteLayout>
        <div className="mx-auto max-w-2xl px-5 py-24 text-center">
          <h1 className="text-2xl font-bold">No lesson pack yet</h1>
          <p className="mt-2 text-muted-foreground">Generate a pack first to view it here.</p>
          <Link to="/create" className="mt-6 inline-flex rounded-full bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground">Create Lesson Pack</Link>
        </div>
      </SiteLayout>
    );
  }

  const onSave = () => {
    savePack(pack);
    toast.success("Saved to your library.");
  };
  const onCopy = async () => {
    await navigator.clipboard.writeText(packToMarkdown(pack));
    toast.success("Lesson pack copied as Markdown.");
  };
  const onMarkdown = () => {
    const blob = new Blob([packToMarkdown(pack)], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url; a.download = `${pack.input.topic.replace(/\s+/g, "-").toLowerCase()}.md`; a.click();
    URL.revokeObjectURL(url);
    toast.success("Markdown export ready.");
  };
  const onPdf = () => { window.print(); toast.success("Use your browser's Save as PDF."); };
  const onPackage = () => toast.success(`EduBox package · ${pack.eduboxPackage.sizeMb} MB · ${pack.eduboxPackage.files.length} files.`);

  return (
    <SiteLayout>
      <section className="mx-auto max-w-5xl px-5 pt-10 pb-16">
        <div className="rounded-3xl border border-border bg-card p-6 md:p-8">
          <div className="flex items-start justify-between gap-4">
            <div>
              <div className="inline-flex items-center gap-2 rounded-full bg-brand-gradient px-3 py-1 text-xs font-semibold text-primary-foreground">
                <Sparkles className="h-3.5 w-3.5" /> Generated by 6 EduBox agents
              </div>
              <h1 className="mt-3 text-3xl font-bold tracking-tight md:text-4xl">{pack.title}</h1>
              <p className="mt-2 text-sm text-muted-foreground">{pack.input.subject} · {pack.input.grade} · {pack.input.language} · {pack.input.difficulty} · {pack.input.country}</p>
            </div>
            <BrandMark className="hidden h-12 w-12 md:block" />
          </div>

          {/* Actions */}
          <div className="mt-6 flex flex-wrap gap-2 print:hidden">
            <ActionBtn icon={Save} label="Save Lesson Pack" onClick={onSave} primary />
            <ActionBtn icon={Copy} label="Copy" onClick={onCopy} />
            <ActionBtn icon={Printer} label="Export as PDF" onClick={onPdf} />
            <ActionBtn icon={Download} label="Export as Markdown" onClick={onMarkdown} />
            <ActionBtn icon={Package} label="EduBox Package Summary" onClick={onPackage} />
          </div>

          <div className="mt-8 space-y-6">
            <Section title="Learning Objectives">
              <ul className="list-disc space-y-1.5 pl-5">{pack.objectives.map((o, i) => <li key={i}>{o}</li>)}</ul>
            </Section>

            <Section title="Teacher Explanation">
              <ul className="space-y-2">{pack.teacherExplanation.map((t, i) => <li key={i} className="text-muted-foreground">{t}</li>)}</ul>
            </Section>

            <Section title="Student Notes">
              <ul className="list-disc space-y-1.5 pl-5">{pack.studentNotes.map((s, i) => <li key={i}>{s}</li>)}</ul>
            </Section>

            <Section title={`Classroom Activity — ${pack.activity.name} · ${pack.activity.duration}`}>
              <div className="text-sm text-muted-foreground"><span className="font-medium text-foreground">Materials:</span> {pack.activity.materials.join(", ")}</div>
              <ol className="mt-3 list-decimal space-y-1.5 pl-5">{pack.activity.steps.map((s, i) => <li key={i}>{s}</li>)}</ol>
            </Section>

            <Section title="Quiz Questions">
              <ol className="space-y-4">
                {pack.quiz.map((q, i) => (
                  <li key={i} className="rounded-2xl border border-border bg-background p-4">
                    <div className="font-medium">Q{i + 1}. {q.q}</div>
                    <div className="mt-2 grid gap-1 text-sm text-muted-foreground sm:grid-cols-2">
                      {q.choices.map((c, j) => <div key={j}>{String.fromCharCode(65 + j)}. {c}</div>)}
                    </div>
                  </li>
                ))}
              </ol>
            </Section>

            <Section title="Answer Key">
              <ol className="list-decimal space-y-1.5 pl-5 text-sm">
                {pack.quiz.map((q, i) => (
                  <li key={i}><span className="font-semibold text-foreground">{String.fromCharCode(65 + q.answer)}</span> <span className="text-muted-foreground">— {q.explain}</span></li>
                ))}
              </ol>
            </Section>

            <Section title="Flashcards">
              <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
                {pack.flashcards.map((f, i) => (
                  <div key={i} className="rounded-2xl border border-border bg-background p-4">
                    <div className="text-sm font-semibold text-foreground">{f.front}</div>
                    <div className="mt-1 text-sm text-muted-foreground">{f.back}</div>
                  </div>
                ))}
              </div>
            </Section>

            <Section title="Revision Summary">
              <p className="text-muted-foreground">{pack.revisionSummary}</p>
            </Section>

            <Section title="Learning Outcome Checklist">
              <ul className="space-y-1.5">
                {pack.outcomeChecklist.map((o, i) => (
                  <li key={i} className="flex items-start gap-2 text-sm"><input type="checkbox" className="mt-1 accent-[color:var(--color-brand-green)]" /> <span>{o}</span></li>
                ))}
              </ul>
            </Section>

            <Section title="EduBox Offline Package">
              <div className="rounded-2xl bg-brand-gradient p-5 text-primary-foreground">
                <div className="flex items-center gap-2 text-sm font-medium opacity-90"><Package className="h-4 w-4" /> {pack.eduboxPackage.sizeMb} MB · {pack.eduboxPackage.syncMode}</div>
                <div className="mt-3 grid gap-1.5 text-sm sm:grid-cols-2">
                  {pack.eduboxPackage.files.map((f) => (
                    <div key={f.name} className="flex items-center justify-between rounded-lg bg-white/10 px-3 py-1.5">
                      <span className="flex items-center gap-2"><FileText className="h-3.5 w-3.5" /> {f.name}</span>
                      <span className="text-xs opacity-80">{f.type} · {f.size}</span>
                    </div>
                  ))}
                </div>
              </div>
            </Section>

            <Section title="Evidence Report Summary">
              <div className="rounded-2xl border border-border bg-background p-5">
                <div className="flex flex-wrap gap-4 text-sm">
                  <Stat label="Expected mastery" value={`${pack.evidence.expectedMastery}%`} />
                  <Stat label="Assessment items" value={String(pack.evidence.assessmentItems)} />
                  <Stat label="Tags" value={pack.evidence.reportingTags.join(", ")} />
                </div>
                <p className="mt-3 text-sm text-muted-foreground">{pack.evidence.summary}</p>
              </div>
            </Section>
          </div>
        </div>
      </section>
    </SiteLayout>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div>
      <h2 className="mb-2 text-lg font-semibold tracking-tight text-foreground">{title}</h2>
      <div className="text-[15px] leading-relaxed text-foreground">{children}</div>
    </div>
  );
}
function Stat({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <div className="text-xs uppercase tracking-wider text-muted-foreground">{label}</div>
      <div className="font-semibold text-foreground">{value}</div>
    </div>
  );
}
function ActionBtn({ icon: Icon, label, onClick, primary }: { icon: React.ComponentType<{ className?: string }>; label: string; onClick: () => void; primary?: boolean }) {
  return (
    <button
      onClick={onClick}
      className={`inline-flex items-center gap-2 rounded-full px-4 py-2 text-sm font-semibold transition ${primary ? "bg-primary text-primary-foreground hover:opacity-90" : "border border-border bg-card text-foreground hover:bg-muted"}`}
    >
      <Icon className="h-4 w-4" /> {label}
    </button>
  );
}