/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestingRouteImport } from './routes/testing'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as GeneratedRouteImport } from './routes/generated'
import { Route as ExamshieldRouteImport } from './routes/examshield'
import { Route as EduboxEvidenceRouteImport } from './routes/edubox-evidence'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreateRouteImport } from './routes/create'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as IndexRouteImport } from './routes/index'

const TestingRoute = TestingRouteImport.update({
  id: '/testing',
  path: '/testing',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneratedRoute = GeneratedRouteImport.update({
  id: '/generated',
  path: '/generated',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamshieldRoute = ExamshieldRouteImport.update({
  id: '/examshield',
  path: '/examshield',
  getParentRoute: () => rootRouteImport,
} as any)
const EduboxEvidenceRoute = EduboxEvidenceRouteImport.update({
  id: '/edubox-evidence',
  path: '/edubox-evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/edubox-evidence': typeof EduboxEvidenceRoute
  '/examshield': typeof ExamshieldRoute
  '/generated': typeof GeneratedRoute
  '/impact': typeof ImpactRoute
  '/saved': typeof SavedRoute
  '/testing': typeof TestingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/edubox-evidence': typeof EduboxEvidenceRoute
  '/examshield': typeof ExamshieldRoute
  '/generated': typeof GeneratedRoute
  '/impact': typeof ImpactRoute
  '/saved': typeof SavedRoute
  '/testing': typeof TestingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/edubox-evidence': typeof EduboxEvidenceRoute
  '/examshield': typeof ExamshieldRoute
  '/generated': typeof GeneratedRoute
  '/impact': typeof ImpactRoute
  '/saved': typeof SavedRoute
  '/testing': typeof TestingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/architecture'
    | '/create'
    | '/dashboard'
    | '/edubox-evidence'
    | '/examshield'
    | '/generated'
    | '/impact'
    | '/saved'
    | '/testing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/architecture'
    | '/create'
    | '/dashboard'
    | '/edubox-evidence'
    | '/examshield'
    | '/generated'
    | '/impact'
    | '/saved'
    | '/testing'
  id:
    | '__root__'
    | '/'
    | '/architecture'
    | '/create'
    | '/dashboard'
    | '/edubox-evidence'
    | '/examshield'
    | '/generated'
    | '/impact'
    | '/saved'
    | '/testing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchitectureRoute: typeof ArchitectureRoute
  CreateRoute: typeof CreateRoute
  DashboardRoute: typeof DashboardRoute
  EduboxEvidenceRoute: typeof EduboxEvidenceRoute
  ExamshieldRoute: typeof ExamshieldRoute
  GeneratedRoute: typeof GeneratedRoute
  ImpactRoute: typeof ImpactRoute
  SavedRoute: typeof SavedRoute
  TestingRoute: typeof TestingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testing': {
      id: '/testing'
      path: '/testing'
      fullPath: '/testing'
      preLoaderRoute: typeof TestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generated': {
      id: '/generated'
      path: '/generated'
      fullPath: '/generated'
      preLoaderRoute: typeof GeneratedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examshield': {
      id: '/examshield'
      path: '/examshield'
      fullPath: '/examshield'
      preLoaderRoute: typeof ExamshieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edubox-evidence': {
      id: '/edubox-evidence'
      path: '/edubox-evidence'
      fullPath: '/edubox-evidence'
      preLoaderRoute: typeof EduboxEvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchitectureRoute: ArchitectureRoute,
  CreateRoute: CreateRoute,
  DashboardRoute: DashboardRoute,
  EduboxEvidenceRoute: EduboxEvidenceRoute,
  ExamshieldRoute: ExamshieldRoute,
  GeneratedRoute: GeneratedRoute,
  ImpactRoute: ImpactRoute,
  SavedRoute: SavedRoute,
  TestingRoute: TestingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
